version: "0.5"
is_strict: true

processes:
  altar:
    command: watchexec --exts go --restart go run .

  request-logger:
    command: watchexec --watch cmd/request_logger --restart devbox run request-logger
