on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # https://github.com/googleapis/release-please-action/releases/tag/v4.2.0
        with:
          release-type: go
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
